name: Node CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Merge PR
        if: success() && github.event_name == 'pull_request'
        run: git merge origin/${{ github.base_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
