name: Node CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: env
      - id: findPr
        uses: ./.github/actions/findPr
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ steps.findPr.outputs.pr }}
      - if: ${{ steps.findPr.outputs.pr }}
        run: echo "This is a PR!"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
