name: Node CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Merge PR
        if: success() && github.event_name == 'pull_request'
        run: git merge ${BASE_REF}
        env:
          BASE_REF: ${{ github.base_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10'
